-- 코드를 작성해주세요
SELECT
    i.ITEM_ID AS ITEM_ID,
    i.ITEM_NAME,
    i.RARITY
FROM
    ITEM_TREE t RIGHT JOIN ITEM_INFO i
    ON t.PARENT_ITEM_ID = i.ITEM_ID
WHERE
    t.ITEM_ID IS NULL
ORDER BY
    i.ITEM_ID DESC;