SELECT 
    YEAR(DIFFERENTIATION_DATE) AS YEAR,
    MAX_SIZE - SIZE_OF_COLONY AS YEAR_DEV,
    ID
FROM 
    ECOLI_DATA
JOIN (
    SELECT 
        YEAR(DIFFERENTIATION_DATE) AS YEAR,
        MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM 
        ECOLI_DATA
    GROUP BY 
        YEAR(DIFFERENTIATION_DATE)
) AS max_sizes ON YEAR(ECOLI_DATA.DIFFERENTIATION_DATE) = max_sizes.YEAR
ORDER BY 
    YEAR ASC, 
    YEAR_DEV ASC;